config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'dashboard_controller/index'
  root 'dashboard#index'
  get "angular_test", to: "angular_test#index"
  resources :customers, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/customer_search_term.rb
class CustomerSearchTerm
  attr_reader :where_clause, :where_args, :order

  def initialize(search_term)
    search_term = search_term.downcase
    @where_clause = ""
    @where_args = {}

    if search_term =~ /@/
      build_for_email_search(search_term)
    else
      build_for_name_search(search_term)
    end
  end

  def build_for_email_search(search_term)
    @where_clause << case_insensitive_search(:first_name)
    @where_args[:first_name] = starts_with(search_term)

    @where_clause << " OR #{case_insensitive_search(:last_name)}"
    @where_args[:last_name] = starts_with(search_term)

    @where_clause << " OR #{case_insensitive_search(:email)}"
    @where_args[:email] = search_term

    @order = "lower(email) = " + ActiveRecord::Base.connection.quote(search_term) + " desc, last_name asc"
  end

  def case_insensitive_search(field_name)
    "lower(#{field_name}) like :#{field_name}"
  end

  def starts_with(search_term)
    search_term + "%"
  end

  def extra_name(email)
    email.gsub(/@.*$/,").gsub(/[0-9]+/,")
  end

  def build_for_name_search(search_term)
    @where_clause << case_insensitive_search(:first_name)
    @where_args[:first_name] = starts_with(search_term)

    @where_clause << " OR #{case_insensitive_search(:last_name)}"
    @where_args[:last_name] = starts_with(search_term)

    @order = "last_name asc"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/angular_test_controller.rb
class AngularTestController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_session


  def set_session
    session[:test1] ||= 2
    session[:test2] ||= 4
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  PAGE_SIZE = 10
  def index
    @key_words = params[:key_words]
    @page = (params[:page] || 0).to_i
    if @key_words.present?
      customer_search_term = CustomerSearchTerm.new(@key_words)
      @customers = Customer.where(customer_search_term.where_clause, customer_search_term.where_args)
        .order(customer_search_term.order).offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
    else
      @customers = Customer.all.offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/angular_test_helper.rb
module AngularTestHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_controller_helper.rb
module DashboardControllerHelper
end

app/views/angular_test/index.html.erb
<article ng-app="angular_test">
  <header>
    <h1 ng-if="name">Hello, {{name}} </h1>
  </header>

  <section>
    <form class="form-inline">
      <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" name="name" type="text", placeholder="Enter your name" autofocus ng-model="name" />
      </div>
    </form>
  </section>

</article>

app/views/customers/_pager.html.erb
<nav>
  <ul class="pager">
    <li class="previous <%= page == 0 ? 'disabled' : '' %>">
      <%= link_to_if page > 0, "&larr; Previous".html_safe, customers_path(key_words: key_words, page: page -1) %>
    </li>

    <li class="next">
      <%= link_to_if page > 0, "Next &rarr;".html_safe, customers_path(key_words: key_words, page: page +1) %>
    </li>
  </ul>
</nav>

app/views/customers/index.html.erb
<header>
  <h1 class=​"h2"​>Customer Search</h1>
​</header>

<section class="search-form">
  <%= form_for :customers, method: :get do |f| %>
    <div class=​"input-group input-group-lg"​>
      <%= label_tag :key_words, nil, class: "sr-only" %>
      <%= text_field_tag :key_words, nil, placeholder: 'Enter your search query here', class: "form-control input-lg" %>
      <span class=​"input-group-btn"​>
        <%= submit_tag "Find Customers", class: "btn btn-primary btn-lg" %>
      </span>
    </div>
  <% end %>
</section>

<section class=​"search-results"​>
  ​<header>
    <h1 class="h3">Result</h1>
  </header>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>LastName</th>
        <th>Email</th>
        <th>Joined</th>
      </tr>
    </thead>
    <tbody>
​      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.first_name %></td>
          <td><%= customer.last_name %></td>
          <td><%= customer.email %></td>
          <td><%= l customer.created_at.to_date %></td>
        </tr>
      <% end %>
​    </tbody>
​  </table>
​</section>

app/views/dashboard/index.html.erb
<section>
  <p> Shine's Dashboard </p>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  <% if notice.present? %>
    <aside class="alert alert-info">
      <%= notice %>
    </aside>
  <% end %>
  <% if alert.present? %>
    <aside class="alert alert-danger"><%= alert %></aside>
  <% end %>
    <%= yield %>
  </body>
</html>